server:
  tomcat.uri-encoding: UTF-8
  tomcat.basedir: /tmp
  port: 8080
  servlet:
    context-path: /demo
qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey: asas
  ## 此处填写你自己的七牛云 secret key
  secretKey: asas
  ## 此处填写你自己的七牛云 bucket
  bucket: asas
  ## 此处填写你自己的七牛云 域名
  prefix:
spring:
  servlet:
    multipart:
      enabled: true
      location: /
      file-size-threshold: 5MB
      max-file-size: 20MB
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:E://tmp/work/Tomcat/localhost/demo/

